Repository Thomas55555/aioautomower, pull requests merged in 2024-06, with the labels that each got.

#330 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#331 Add badges
  README.md
Labels: documentation

#327 add start_in_workarea
  example.py
  src/aioautomower/session.py
  tests/test_session.py
Labels: enhancement

#274 Add inactive reasons
  .gitignore
  src/aioautomower/model.py
  tests/__snapshots__/test_high_feature_mower_model.ambr
  tests/__snapshots__/test_low_feature_mower_model.ambr
  tests/fixtures/high_feature_mower.json
  tests/fixtures/low_feature_mower.json
  tests/fixtures/status_event.json
  tests/fixtures/status_event_battery_50.json
  tests/fixtures/status_event_mower2.json
Labels: enhancement

#336 Add new attributes (is_error_confirmable, work_area_id)
  src/aioautomower/model.py
  tests/__snapshots__/test_high_feature_mower_model.ambr
  tests/__snapshots__/test_low_feature_mower_model.ambr
  tests/fixtures/high_feature_mower.json
Labels: enhancement

#338 Accept duration as timedelta instead of int
  example.py
  src/aioautomower/session.py
  src/aioautomower/utils.py
  tests/test_session.py
Labels: enhancement, breaking-change

#332 handle bad request
  src/aioautomower/auth.py
  src/aioautomower/exceptions.py
Labels: enhancement

#344 remove _secrets.yaml from src
  .gitignore
  _secrets.yaml
  example.py
Labels: enhancement, breaking-change

#348 fix wrong default for is_error_confirmable
  src/aioautomower/model.py
  tests/__snapshots__/test_low_feature_mower_model.ambr
Labels: bugfix

#349 Import ical parts
  poetry.lock
  pyproject.toml
  src/aioautomower/__init__.py
  src/aioautomower/helper.py
Labels: enhancement

#351 Remove ical imports again
  poetry.lock
  pyproject.toml
  src/aioautomower/__init__.py
  src/aioautomower/helper.py
Labels: dependencies, breaking-change

#357 Create LICENSE
  LICENSE
  README.md
  pyproject.toml
Labels: documentation

#359 Add classifiers
  pyproject.toml
Labels: documentation

#362 Import ical again
  poetry.lock
  pyproject.toml
  src/aioautomower/model.py
Labels: enhancement

#364 improve snapshots
  tests/__snapshots__/test_high_feature_mower_model.ambr
  tests/__snapshots__/test_jwt_model.ambr
  tests/__snapshots__/test_low_feature_mower_model.ambr
  tests/conftest.py
  tests/syrupy.py
Labels: refactor

#365 Ensure current event is on top
  src/aioautomower/model.py
Labels: bugfix
