Repository Thomas55555/aioautomower, pull requests merged in 2024-04, with the labels that each got.

#266 Remove secrets from example.py
  .gitignore
  poetry.lock
  pyproject.toml
  src/aioautomower/_secrets.yaml
  src/aioautomower/example.py
Labels: breaking-change

#268 Return next start datetime and error datetime naive
  pyproject.toml
  src/aioautomower/example.py
  src/aioautomower/model.py
  src/aioautomower/utils.py
  tests/__snapshots__/test_high_feature_mower_model.ambr
  tests/__snapshots__/test_low_feature_mower_model.ambr
  tests/__snapshots__/test_session.ambr
  tests/test_high_feature_mower_model.py
  tests/test_low_feature_mower_model.py
Labels: breaking-change

#269 return serial number as string
  src/aioautomower/model.py
Labels: enhancement

#270 Add errors_confirm API
  src/aioautomower/session.py
  tests/test_session.py
Labels: enhancement

#272 Return local timestamps as datetime UTC
  src/aioautomower/model.py
  tests/__snapshots__/test_high_feature_mower_model.ambr
  tests/__snapshots__/test_low_feature_mower_model.ambr
  tests/__snapshots__/test_session.ambr
Labels: enhancement

#275 Update readme
  README.md
Labels: documentation

#281 Improve typing
  pyproject.toml
  src/aioautomower/auth.py
  src/aioautomower/example.py
  src/aioautomower/session.py
Labels: enhancement

#284 Always return a workarea name
  src/aioautomower/model.py
  tests/__snapshots__/test_high_feature_mower_model.ambr
  tests/__snapshots__/test_session.ambr
Labels: enhancement

#255 Test update data
  src/aioautomower/session.py
  tests/__snapshots__/test_session.ambr
  tests/fixtures/settings_event.json
  tests/fixtures/status_event.json
  tests/test_session.py
Labels: refactor
